AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata:

Parameters:

Mappings:

Conditions:

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      MfaConfiguration: "OFF"
      UserPoolName: t3-userpool
      UserPoolTags: Json
      Schema: 
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: givenName
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: usrName
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: displayName
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: usrName
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: objectidentifier
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: tenantid
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          Name: identityprovider

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      UserPoolId: !Ref UserPool
      Domain: !Sub "t3"
    DependsOn: UserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      AccessTokenValidity: 5
      IdTokenValidity: 5
      RefreshTokenValidity: 7
      TokenValidityUnits: 
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes: 
        - openid
      CallbackURLs: 
        - localhost:
      ClientName: !Sub "t3_userpool_client"
      DefaultRedirectURI: String
      EnablePropagateAdditionalUserContextData: Boolean
      EnableTokenRevocation: Boolean
      ExplicitAuthFlows: 
        - String
      GenerateSecret: Boolean
      LogoutURLs: 
        - String
      PreventUserExistenceErrors: String
      ReadAttributes: 
        - String
      SupportedIdentityProviders: 
        - String
      UserPoolId: String
      WriteAttributes: 
        - String


Outputs:
