version: "3"

services:
    t3-dev:
        build:
            context: ./t3-dev
            dockerfile: Dockerfile
        restart: always
        tty: true
        volumes:
            - ..:/homde/node:cached